name = "tauri-update-server"
compatibility_date = "2024-05-10"
main = "src/index.ts"

[vars]
GITHUB_ACCOUNT = 'killeencode'
GITHUB_REPO = 'brancato'
GITHUB_TOKEN = '' # Optional - used with private repos